name: Hola Pipeline
on:
  push:
    branches: [main]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Bienvenida
        run: |
          echo "¡Hola DevOps!"
          echo "Esta es mi primera pipeline, y acabo de editarlo"
          echo "¿SALIO BIEN?"
          date
          uname -a
